sudo: false
language: node_js
node_js:
- '8.11.3'
branches:
  only:
  - site
# Disable caching due to bringing in @types packages that
# conflict with Typedoc builds for Excalibur
cache: false
env:
  global:
  - GH_REF: github.com/excaliburjs/excaliburjs.github.io.git
  - GH_RELEASE_TAG: master
before_install:
- gem install sass -v 3.4.24
- npm run docs
script:
- npm run build
after_success:
- ! '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || npm run deploy'
notifications:
  slack:
    secure: smD+hnNSy3lhrD9zuDabdItTErnVh465hoCJMovHN/+8+y0vVu41Z9UdaFcZga1QRhwf9fnqgs2UmeE52B76ptntvbg1YZfQ7u8RlAgy6Tp7nXrLOoso0TX05pvHgL27qXzmZyZQilj2bS0pUPI0OS2Nx19cUtNoDU89boRI1VU=
